### ISSUE TITLE
SOL Governors for CRY and CES

### ISSUE THREAD

**Issue by Yard1** [Scroup/equestria_dev#36]

**Comment by Scroup** [comment]
Sunrise Sparkle for CRY, boy.
The priest girl also is an advisor somewhere in the south, she could become a new leader of CES, for the sun crusader.

**Comment by Yard1** [comment]
Sunrise will be surely an option, but I don't want to deprive SOL of all their advisors :(

**Comment by Yard1** [comment]
CES will get annexed, CRY gets Sparkle.
